apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: simple-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: fkdevops/kubernetes-images
          ports:
            - name: httpport
              containerPort: 80
